### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AlexTheGoat69** [Voxel-Fox-Ltd/UpgradeChatPy#1]
How would I go about making a event for an order?

**Comment by 4Kaylum** [comment]
Could you elaborate on what you mean?

This lib deals primarily with the UpgradeChat API rather than their webhook system.

**Comment by AlexTheGoat69** [comment]
> Could you elaborate on what you mean?
> 
> 
> 
> This lib deals primarily with the UpgradeChat API rather than their webhook system.

Like isn't it possible to use this library to check when someone purchases something through upgrade chat and send a message to discord that contains the buyer user.id and what exactly they purchased on upgrade chat or is that only with their webhook system?

**Comment by AlexTheGoat69** [comment]
Or is this only to like retrieve data on already existing orders

**Comment by 4Kaylum** [comment]
This can only retrieve information on existing orders. If you're looking for immediate notification on an order recieve, then yes you would be looking into the webhook system.

**Comment by AlexTheGoat69** [comment]
ah make sense, I was very confused thanks for informing me!
